version: '2'

services:
  db:
    image: postgres
    ports:
      - "5432:5432"
  web:
    build: .
    command: uwsgi --http :8001 --module app.wsgi 
    volumes:
      - .:/code
    ports:
      - "80:80"
    depends_on:
      - db
